name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-Unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Execute Unit tests
      run: npm run test:unit
    - name: Display SoftUnu username
      run: echo "M.Chipilov"

  execute-test-UI:
      needs: build-and-Unit-test
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install NPM dependencies
        run: npm install
      - name: Install Playwright brousers
        run: npx playwright install
      - name: Start the application
        run: npm run start &
      - name: Execute UI tests
        run: npm run test:ui